### ISSUE TITLE
Support Redis modules

### ISSUE THREAD

**Issue by jaredpetersen** [jaredpetersen/kafka-connect-redis#13]
Add support for arbitrary commands from Redis modules.

Request originally submitted by @bcashier here: https://github.com/jaredpetersen/kafka-connect-redis/issues/11

**Comment by jaredpetersen** [comment]
@bcashier We now support Redis modules! Check out the demo for an example that shows the connector in action with RedisTimeSeries.

**Comment by bcashier** [comment]
Thank you for this awesome work !!!!

I will give it a try and let you know ! Thank you for keeping your word !
